del *.obj
del lores\*.obj
del lores\*.bin
del lores\*.res
del hires\*.obj
del hires\*.bin
del hires\*.res
del rc640480\*.obj
del rc640480\*.bin
del rc640480\*.res
del blkwhite\*.obj
del blkwhite\cgaherc\*.obj
del blkwhite\cgaherc\cga\*.obj
del blkwhite\cgaherc\cga\*.drv
del blkwhite\cgaherc\cga\*.sym
del blkwhite\cgaherc\cga\*.map
del blkwhite\cgaherc\cga\*.res
del blkwhite\cgaherc\compaq\*.obj
del blkwhite\cgaherc\compaq\*.drv
del blkwhite\cgaherc\compaq\*.map
del blkwhite\cgaherc\compaq\*.sym
del blkwhite\cgaherc\compaq\*.res
del blkwhite\cgaherc\hercules\*.obj
del blkwhite\cgaherc\hercules\*.drv
del blkwhite\cgaherc\hercules\*.map
del blkwhite\cgaherc\hercules\*.sym
del blkwhite\cgaherc\hercules\*.res
del blkwhite\cgaherc\olivetti\*.obj
del blkwhite\cgaherc\olivetti\*.drv
del blkwhite\cgaherc\olivetti\*.map
del blkwhite\cgaherc\olivetti\*.sym
del blkwhite\cgaherc\olivetti\*.res
del blkwhite\ega\*.obj
del blkwhite\ega\egamono\*.obj
del blkwhite\ega\egamono\*.drv
del blkwhite\ega\egamono\*.map
del blkwhite\ega\egamono\*.sym
del blkwhite\ega\egamono\*.res
del blkwhite\ega\egahibw\*.obj
del blkwhite\ega\egahibw\*.drv
del blkwhite\ega\egahibw\*.map
del blkwhite\ega\egahibw\*.sym
del blkwhite\ega\egahibw\*.res
del blkwhite\ega\icarus\*.obj
del blkwhite\ega\icarus\*.drv
del blkwhite\ega\icarus\*.map
del blkwhite\ega\icarus\*.sym
del blkwhite\ega\icarus\*.res
del color\*.obj
del color\ega\*.obj
del color\ega\egalores\*.obj
del color\ega\egalores\*.drv
del color\ega\egalores\*.map
del color\ega\egalores\*.sym
del color\ega\egalores\*.res
del color\ega\egahires\*.obj
del color\ega\egahires\*.drv
del color\ega\egahires\*.map
del color\ega\egahires\*.sym
del color\ega\egahires\*.res
del color\ega\vga\*.obj
del color\ega\vga\*.drv
del color\ega\vga\*.map
del color\ega\vga\*.sym
del color\ega\vga\*.res
del color\ega\vga450\*.obj
del color\ega\vga450\*.drv
del color\ega\vga450\*.map
del color\ega\vga450\*.sym
del color\ega\vga450\*.res
