#define IDD_ADD           111
#define IDD_CONNECTIONS   101
#define IDD_DEVICEREM     117
#define IDD_DEVMODE       102
#define IDD_DRVVER        103
#define IDD_ERROR         104
#define IDD_FORCE         119
#define IDD_GETNETCONS    105
#define IDD_LOCALNAME     114
#define IDD_NETLIST       106
#define IDD_NETPATHNAME   112
#define IDD_NETTYPE       107
#define IDD_PASSWORD      113
#define IDD_PRINTING      108
#define IDD_REMOVE        120
#define IDD_SPECVER       109
#define IDD_USER          110
#define IDD_VSCROLL	  121
#define IDM_EDITFIELD	  200
#define IDD_CORRECTTEXT   122
#define IDD_DRIVERTEXT	  123
#define IDD_ERRORCODELIST 124
