#define E_GENERAL				0
#define E_TOOMANYAPDS			1
#define E_MISSING				2
#define E_ILLEGALCHARACTER		3
#define E_ILLEGALFILENAME		4
#define E_MISSINGKEYWORDAFTER	5
#define E_MISSINGAFTER			6
#define E_ILLEGALKEYWORDAFTER	7
#define E_ILLEGALSTRINGAFTER	8
#define E_TRANSVERSE			9
#define E_MISSINGKEYWORD		10
#define E_TRUEFALSE				11
#define E_INCOMPLETE			12
#define E_INVERSE				13
#define E_FIND					14
#define E_MAKE					15
#define E_OPEN					16
#define E_CLOSE					17
#define E_WRITE					18
#define E_READ					19
#define E_READAPD				20
#define E_TOKENTOOLONG			21
#define E_STRINGTOOLONG			22
#define E_LINETOOLONG			23
#define E_EOF					24
#define E_END					25
#define E_UNTERMINATEDSTRING	26
#define E_MEMORY				27
#define E_MEMORY1				28
#define E_ILLEGALORMISSING		29
#define E_POSSIBLENONNUMBER		30
#define E_NEGATIVEMARGIN		31
#define E_TRANSLATION			32
