#define BINARY                   31
#define COPIES                   22
#define EDITFIELD                20
#define HANDSHAKE_HARDWARE       801
#define ID_SCALE                 30
#define IDAPLTALK                26
#define IDHELP                	34
#define IDFONTS                  32
#define IDOPTIONS                28
#define IDABOUT                29
#define HANDSHAKE_SOFTWARE   800
#define HEADER_NO            521
#define HEADER_YES           520
#define OP_ERROR_FILE        701
#define OP_ERROR_PRINTER     700
#define OP_ERROR             532
#define OP_FILE              900
#define OP_HANDSHAKE         531
#define OP_HEADER            530
#define DEFAULT_MARGINS		510
#define ZERO_MARGINS		511
#define TILE_MARGINS		512
#define JOBTIMEOUT               23
#define LANDSCAPE                11
#define OP_HEADER_FILE           601
#define OP_HEADER_PRINTER        600
#define PORTRAIT                 10
#define PRINTERLIST              21
#define SIZELIST                 24
#define SOURCELIST               25
#define USE_COLOR                27
#define USE_EPS                  29
#define TO_PRINTER               30
#define TO_EPS	                 31
#define FILE_TEXT                32
#define FILE_EDIT                33
#define ADD_PRINTER              35
#define IDICON			36

#define PRINTER_LIST	100
#define ID_EDIT		101
#define STATUS_MSG	102
#define INSTALL		103
